import os
ENVIRONMENT=os.getenv('ENVIRONMENT','development')
DEBUG=os.getenv('DEBUG','true').lower() in ('1','true','yes')
DATABASE_URL=os.getenv('DATABASE_URL')
REDIS_URL=os.getenv('REDIS_URL')
SECRET_KEY=os.getenv('SECRET_KEY','change-me')
ALGORITHM='HS256'
ACCESS_TOKEN_EXPIRE_MINUTES=1440
OPENROUTER_API_BASE=os.getenv('OPENROUTER_API_BASE','')
OPENROUTER_API_KEY=os.getenv('OPENROUTER_API_KEY','')
OPENROUTER_MODEL=os.getenv('OPENROUTER_MODEL','')
TELEGRAM_BOT_TOKEN=os.getenv('TELEGRAM_BOT_TOKEN','')
TELEGRAM_CHAT_ID=os.getenv('TELEGRAM_CHAT_ID','')
DEFAULT_TIMEFRAME=os.getenv('DEFAULT_TIMEFRAME','1h')
DEFAULT_INITIAL_CAPITAL=float(os.getenv('DEFAULT_INITIAL_CAPITAL','10000'))
MAX_POSITION_PCT=float(os.getenv('MAX_POSITION_PCT','2'))
MAX_DRAWDOWN_PCT=float(os.getenv('MAX_DRAWDOWN_PCT','10'))
DAILY_LOSS_LIMIT_PCT=float(os.getenv('DAILY_LOSS_LIMIT_PCT','5'))
